<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][4]['training_application.attachment'] = array(
	'f_id' => 2,
	'fg_id' => 4,
	'label' => 'Attachment',
	'description' => '',
	'table' => 'training_application',
	'column' => 'attachment',
	'uitype_id' => 8,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 13,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.note'] = array(
	'f_id' => 13,
	'fg_id' => 4,
	'label' => 'NOTE: (If Training will exceed in 1 Month):',
	'description' => '',
	'table' => 'training_application',
	'column' => 'note',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 12,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.competency'] = array(
	'f_id' => 12,
	'fg_id' => 4,
	'label' => 'Competency',
	'description' => '',
	'table' => 'training_application',
	'column' => 'competency',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_category',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'category',
		'value' => 'category_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.areas_development'] = array(
	'f_id' => 11,
	'fg_id' => 4,
	'label' => 'Areas for Development',
	'description' => '',
	'table' => 'training_application',
	'column' => 'areas_development',
	'uitype_id' => 10,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'performance_appraisal_areas_development',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'appraisal_areas_development',
		'value' => 'appraisal_areas_development_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.total_investment_pgsa'] = array(
	'f_id' => 10,
	'fg_id' => 4,
	'label' => 'Estimate Investment (Subject for revision by HR):',
	'description' => '',
	'table' => 'training_application',
	'column' => 'total_investment_pgsa',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.total_training_hour'] = array(
	'f_id' => 9,
	'fg_id' => 4,
	'label' => 'Total Training Hours',
	'description' => '',
	'table' => 'training_application',
	'column' => 'total_training_hour',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.venue'] = array(
	'f_id' => 8,
	'fg_id' => 4,
	'label' => 'Venue',
	'description' => '',
	'table' => 'training_application',
	'column' => 'venue',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.training_provider'] = array(
	'f_id' => 7,
	'fg_id' => 4,
	'label' => 'Training Provider',
	'description' => '',
	'table' => 'training_application',
	'column' => 'training_provider',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_provider',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'provider',
		'value' => 'provider_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.training_course_id'] = array(
	'f_id' => 6,
	'fg_id' => 4,
	'label' => 'Training Course',
	'description' => '',
	'table' => 'training_application',
	'column' => 'training_course_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_course',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'course',
		'value' => 'course_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.date_to'] = array(
	'f_id' => 5,
	'fg_id' => 4,
	'label' => 'Date of Program (To)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.date_from'] = array(
	'f_id' => 4,
	'fg_id' => 4,
	'label' => 'Date of Program (From)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.training_type'] = array(
	'f_id' => 3,
	'fg_id' => 4,
	'label' => 'Training Type',
	'description' => '',
	'table' => 'training_application',
	'column' => 'training_type',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'training_type',
		'value' => 'type_id',
		'textual_value_column' => ''
	)
);
