<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][2]['time_form_balance_setup_policy.leave_reset_date'] = array(
	'f_id' => 12,
	'fg_id' => 2,
	'label' => 'Leave Reset Date',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'leave_reset_date',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_form_balance_setup_policy.prorated'] = array(
	'f_id' => 11,
	'fg_id' => 2,
	'label' => 'Pro-rated',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'prorated',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_form_balance_setup_policy.max_credit'] = array(
	'f_id' => 10,
	'fg_id' => 2,
	'label' => 'Maximum Credit',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'max_credit',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_form_balance_setup_policy.credit'] = array(
	'f_id' => 9,
	'fg_id' => 2,
	'label' => 'Credit',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'credit',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_form_balance_setup_policy.credit_16_31'] = array(
	'f_id' => 8,
	'fg_id' => 2,
	'label' => ' Credit (16 to 31 of the month)',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'credit_16_31',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_form_balance_setup_policy.credit_1_15'] = array(
	'f_id' => 7,
	'fg_id' => 2,
	'label' => 'Credit (1 to 15 of the month)',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'credit_1_15',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_form_balance_setup_policy.accumulation_type'] = array(
	'f_id' => 6,
	'fg_id' => 2,
	'label' => 'Accumulation Type',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'accumulation_type',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => '',
		'multiple' => 0,
		'group_by' => '',
		'label' => '',
		'value' => '',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['time_form_balance_setup_policy.form_id'] = array(
	'f_id' => 5,
	'fg_id' => 2,
	'label' => 'Leave Type',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'form_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'time_form',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'form',
		'value' => 'form_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['time_form_balance_setup_policy.description'] = array(
	'f_id' => 4,
	'fg_id' => 2,
	'label' => 'Description',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'description',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'Required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][2]['time_form_balance_setup_policy.job_grade_ids'] = array(
	'f_id' => 3,
	'fg_id' => 2,
	'label' => 'Rank',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'job_grade_ids',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_job_grade_level',
		'multiple' => 1,
		'group_by' => '',
		'label' => 'job_grade_id',
		'value' => 'job_level',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['time_form_balance_setup_policy.employment_status_ids'] = array(
	'f_id' => 3,
	'fg_id' => 2,
	'label' => 'Employment Status',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'employment_status_ids',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_status',
		'multiple' => 1,
		'group_by' => '',
		'label' => 'employment_status_id',
		'value' => 'employment_status',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['time_form_balance_setup_policy.employment_type_ids'] = array(
	'f_id' => 2,
	'fg_id' => 2,
	'label' => 'Employee Type',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'employment_type_ids',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'partners_employment_type',
		'multiple' => 1,
		'group_by' => '',
		'label' => 'employment_type',
		'value' => 'employment_type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][2]['time_form_balance_setup_policy.company_ids'] = array(
	'f_id' => 1,
	'fg_id' => 2,
	'label' => 'Company',
	'description' => '',
	'table' => 'time_form_balance_setup_policy',
	'column' => 'company_ids',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users_company',
		'multiple' => 1,
		'group_by' => '',
		'label' => 'company',
		'value' => 'company_id',
		'textual_value_column' => ''
	)
);
