SELECT 
	`u`.`user_id` AS `employee`,
	`pp`.`company_id` AS `company_id`,
	`uc`.`company` AS `company`,
	`uc`.`address` AS `address`,
	`uc`.`city` AS `city`,
	`u`.`user_id` AS `user_id`,
	`p`.`id_number` AS `id_number`,
	`u`.`full_name` AS `full_name`,
	`up`.`department_id` AS `department_id`,
	`d`.`department_code` AS `department_code`,
	`uproj`.`project_id` AS `project_id`,
	`uproj`.`project_code` AS `project_code`,
	`uproj`.`project` AS `project`,
	`prt`.`payroll_rate_type_id` AS `payroll_rate_type_id`,
	`prt`.`payroll_rate_type` AS `payroll_rate_type`,
	0 AS `adjustment`,
	0 AS `other_taxable`,	
	(CASE WHEN (`pct`.`transaction_code` = 'ABSENCES') THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `absent_tardy`,
	0 AS `sss`,
	0 AS `philhealth`,
	0 AS `pag_ibig`,
	0 AS `nontax_income`,
	(CASE WHEN (`pct`.`transaction_code` = 'REGND') THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `nd`,
	0 AS `reg`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_x8`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `sp`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `sp_x8`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_x8`,
	ROUND((((AES_DECRYPT(`pp`.`salary`,`encryption_key`()) * 12) / `pp`.`total_year_days`) / 8),2) AS `hourly_rate`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `legal`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `legal_x8`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_legal`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_leg_x8`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'REGOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `nd_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `reg_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `sp_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `sp_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `legal_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `legal_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_legal_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_leg_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `nd_hrs`,
	0 AS `reg_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_x8_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `sp_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `sp_x8_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_x8_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `legal_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `legal_x8_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_legal_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_leg_x8_hrs`,
	0 AS `health_card`,
	0 AS `other_deduction_one`,
	0 AS `other_deduction_two`,
	0 AS `other_deduction_three`,
	0 AS `sss_sal_loan_payments`,
	0 AS `sss_cal_loan_payments`,
	0 AS `hdmf_sal_loan_payments`,
	0 AS `hdmf_cal_loan_payments`,
	0 AS `company_loan_payments`,
	0 AS `sss_sal_loan_balance`,
	0 AS `sss_cal_loan_balance`,
	0 AS `hdmf_sal_loan_balance`,
	0 AS `hdmf_cal_loan_balance`,
	0 AS `tax_status`,
	0 AS `ytd_sss`,
	0 AS `ytd_philhealth`,
	0 AS `ytd_pag_ibig`,
	`pp`.`tin` AS `tin`,
	`pt`.`transaction_label` AS `transaction_label`,
	`ptc`.`transaction_class_code` AS `transaction_class_code`,
	`pt`.`transaction_code` AS `transaction_code`,
	(CASE WHEN (`pct`.`transaction_code` IN ('ABSENCES','ABSENCES_ADJ','LWOP','LWOP_ADJ')) THEN CONCAT(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),' (',`getabsent`(`t`.`payroll_date`,`u`.`user_id`,`pct`.`transaction_code`),') ') ELSE AES_DECRYPT(`pct`.`quantity`,`encryption_key`()) END) AS `qty`,
	ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) AS `amount`,
	`pct`.`transaction_type_id` AS `transaction_type_id`,
	(CASE WHEN (`pct`.`transaction_type_id` IN (1,2,6,7,8)) THEN 'Earnings' WHEN (`pct`.`transaction_type_id` IN (3,4,5)) THEN 'Deductions' WHEN (`pct`.`transaction_code` = 'NETPAY') THEN 'Netpay' ELSE '' END) AS `group`,
	(CASE WHEN ((`ptc`.`transaction_class_code` IN ('LOAN_AMORTIZATION','LOAN_INTEREST')) AND (`ptc`.`government_mandated` = 0)) THEN 'Loan' WHEN ((`ptc`.`government_mandated` = 1) OR (`ptc`.`transaction_class_code` = 'WHTAX')) THEN 'government' WHEN (`ptc`.`transaction_class_code` = 'OVERTIME') THEN 'overtime' WHEN ((`ptc`.`transaction_class_code` IN ('ABSENCES','DEDUCTION_LATE','DEDUCTION_UNDERTIME')) OR (`pt`.`transaction_code` = 'LWOP')) THEN 'attnd_ded' WHEN (`pt`.`transaction_type_id` = 8) THEN 'Bonus' WHEN (`pt`.`transaction_type_id` IN (2,6)) THEN 'Benefits' WHEN ((`pt`.`transaction_type_id` = 1) AND (`pt`.`transaction_id` <> 1)) THEN 'Earnings' WHEN (`pt`.`transaction_id` = 1) THEN 'salary' WHEN (`pt`.`transaction_code` = 'NETPAY') THEN 'Netpay' ELSE (CASE WHEN (`pt`.`transaction_type_id` IN (3,4,5)) THEN 'Oth_ded' WHEN (`pt`.`transaction_type_id` IN (1,2,6,7,8)) THEN 'Oth_inc' ELSE '' END) END) AS `type`,
	(CASE WHEN (`ptc`.`transaction_class_code` = 'LOAN_AMORTIZATION') THEN `pct`.`record_id` ELSE '' END) AS `record_id`,
	(CASE WHEN (`ptc`.`transaction_class_code` = 'LOAN_AMORTIZATION') THEN ROUND(AES_DECRYPT(`pl`.`beginning_balance`,`encryption_key`()),2) ELSE 0 END) AS `beginning_balance`,
	(CASE WHEN (`ptc`.`transaction_class_code` = 'LOAN_AMORTIZATION') THEN ROUND(AES_DECRYPT(`pl`.`running_balance`,`encryption_key`()),2) ELSE 0 END) AS `running_balance`,
	`t`.`payroll_date` AS `payroll_date`,
	`t`.`date_from` AS `date_from`,
	`t`.`date_to` AS `date_to`,
	`tc`.`taxcode` AS `taxcode`,
	`getcompany_contact`(`pct`.`company_id`,'Phone') AS `phone_no`,
	`getcompany_contact`(`pct`.`company_id`,'Fax') AS `fax_no` 
FROM ((((((((((((((`ww_payroll_current_transaction` `pct` 
		JOIN `ww_users` `u` ON((`pct`.`employee_id` = `u`.`user_id`))) 
		JOIN `ww_partners` `p` ON((`u`.`user_id` = `p`.`user_id`))) 
		JOIN `ww_partners_personal` `ppe` ON((`p`.`partner_id` = `ppe`.`partner_id`))) 
		JOIN `ww_taxcode` `tc` ON((`tc`.`taxcode_id` = `ppe`.`key_value`))) 
		JOIN `ww_users_profile` `up` ON((`u`.`user_id` = `up`.`user_id`))) 
		JOIN `ww_payroll_partners` `pp` ON((`pp`.`user_id` = `u`.`user_id`))) 
		JOIN `ww_users_department` `d` ON((`d`.`department_id` = `up`.`department_id`))) 
		JOIN `ww_users_company` `uc` ON((`uc`.`company_id` = `pp`.`company_id`))) 
		LEFT JOIN `ww_payroll_period` `t` ON((`t`.`payroll_period_id` = `pct`.`period_id`))) 
		LEFT JOIN `ww_payroll_transaction` `pt` ON((`pt`.`transaction_id` = `pct`.`transaction_id`))) 
		LEFT JOIN `ww_payroll_transaction_class` `ptc` ON((`pt`.`transaction_class_id` = `ptc`.`transaction_class_id`))) 
		LEFT JOIN `ww_payroll_partners_loan` `pl` ON((`pl`.`partner_loan_id` = `pct`.`record_id`))) 
		LEFT JOIN `ww_users_project` `uproj` ON((`pct`.`project_id` = `uproj`.`project_id`))) 
		LEFT JOIN `ww_payroll_rate_type` `prt` ON((`pct`.`payroll_rate_type_id` = `prt`.`payroll_rate_type_id`))) 
		WHERE ((`pct`.`on_hold` = 0) AND (`ppe`.`key` = 'taxcode')) 
UNION ALL 
	SELECT `u`.`user_id` AS `employee`,
	`pp`.`company_id` AS `company_id`,
	`uc`.`company` AS `company`,
	`uc`.`address` AS `address`,
	`uc`.`city` AS `city`,
	`u`.`user_id` AS `user_id`,
	`p`.`id_number` AS `id_number`,
	`u`.`full_name` AS `full_name`,
	`up`.`department_id` AS `department_id`,
	`d`.`department_code` AS `department_code`,
	`uproj`.`project_id` AS `project_id`,
	`uproj`.`project_code` AS `project_code`,
	`uproj`.`project` AS `project`,
	`prt`.`payroll_rate_type_id` AS `payroll_rate_type_id`,
	`prt`.`payroll_rate_type` AS `payroll_rate_type`,
	0 AS `adjustment`,
	0 AS `other_taxable`,	
	(CASE WHEN (`pct`.`transaction_code` = 'ABSENCES') THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `absent_tardy`,
	0 AS `sss`,
	0 AS `philhealth`,
	0 AS `pag_ibig`,
	0 AS `nontax_income`,
	(CASE WHEN (`pct`.`transaction_code` = 'REGND') THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `nd`,
	0 AS `reg`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_x8`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `sp`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `sp_x8`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_x8`,
	ROUND((((AES_DECRYPT(`pp`.`salary`,`encryption_key`()) * 12) / `pp`.`total_year_days`) / 8),2) AS `hourly_rate`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `legal`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `legal_x8`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_legal`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_leg_x8`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'REGOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `nd_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `reg_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `sp_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `sp_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `legal_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `legal_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_ND')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_legal_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `rest_leg_x8_otnd`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_ND_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) ELSE 0 END) AS `nd_hrs`,
	0 AS `reg_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'RDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_x8_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `sp_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPEOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `sp_x8_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'SPERDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_sp_x8_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `legal_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `legal_x8_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_legal_hrs`,
	(CASE WHEN ((`ptc`.`transaction_class_code` = 'OVERTIME') AND (`pct`.`transaction_code` = 'LEGRDOT_EXCESS')) THEN ROUND(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),2) ELSE 0 END) AS `rest_leg_x8_hrs`,
	0 AS `health_card`,
	0 AS `other_deduction_one`,
	0 AS `other_deduction_two`,
	0 AS `other_deduction_three`,
	0 AS `sss_sal_loan_payments`,
	0 AS `sss_cal_loan_payments`,
	0 AS `hdmf_sal_loan_payments`,
	0 AS `hdmf_cal_loan_payments`,
	0 AS `company_loan_payments`,
	0 AS `sss_sal_loan_balance`,
	0 AS `sss_cal_loan_balance`,
	0 AS `hdmf_sal_loan_balance`,
	0 AS `hdmf_cal_loan_balance`,
	0 AS `tax_status`,
	0 AS `ytd_sss`,
	0 AS `ytd_philhealth`,
	0 AS `ytd_pag_ibig`,
	`pp`.`tin` AS `tin`,
	`pt`.`transaction_label` AS `transaction_label`,
	`ptc`.`transaction_class_code` AS `transaction_class_code`,
	`pt`.`transaction_code` AS `transaction_code`,
	(CASE WHEN (`pct`.`transaction_code` IN ('ABSENCES','ABSENCES_ADJ','LWOP','LWOP_ADJ')) THEN CONCAT(AES_DECRYPT(`pct`.`quantity`,`encryption_key`()),' (',`getabsent`(`t`.`payroll_date`,`u`.`user_id`,`pct`.`transaction_code`),') ') ELSE AES_DECRYPT(`pct`.`quantity`,`encryption_key`()) END) AS `qty`,ROUND(AES_DECRYPT(`pct`.`amount`,`encryption_key`()),2) AS `amount`,
	`pct`.`transaction_type_id` AS `transaction_type_id`,
	(CASE WHEN (`pct`.`transaction_type_id` IN (1,2,6,7,8)) THEN 'Earnings' WHEN (`pct`.`transaction_type_id` IN (3,4,5)) THEN 'Deductions' WHEN (`pct`.`transaction_code` = 'NETPAY') THEN 'Netpay' ELSE '' END) AS `group`,
	(CASE WHEN ((`ptc`.`transaction_class_code` IN ('LOAN_AMORTIZATION','LOAN_INTEREST')) AND (`ptc`.`government_mandated` = 0)) THEN 'Loan' WHEN ((`ptc`.`government_mandated` = 1) OR (`ptc`.`transaction_class_code` = 'WHTAX')) THEN 'government' WHEN (`ptc`.`transaction_class_code` = 'OVERTIME') THEN 'overtime' WHEN ((`ptc`.`transaction_class_code` IN ('ABSENCES','DEDUCTION_LATE','DEDUCTION_UNDERTIME')) OR (`pt`.`transaction_code` = 'LWOP')) THEN 'attnd_ded' WHEN (`pt`.`transaction_type_id` = 8) THEN 'Bonus' WHEN (`pt`.`transaction_type_id` IN (2,6)) THEN 'Benefits' WHEN ((`pt`.`transaction_type_id` = 1) AND (`pt`.`transaction_id` <> 1)) THEN 'Earnings' WHEN (`pt`.`transaction_id` = 1) THEN 'salary' WHEN (`pt`.`transaction_code` = 'NETPAY') THEN 'Netpay' ELSE (CASE WHEN (`pt`.`transaction_type_id` IN (3,4,5)) THEN 'Oth_ded' WHEN (`pt`.`transaction_type_id` IN (1,2,6,7,8)) THEN 'Oth_inc' ELSE '' END) END) AS `type`,
	(CASE WHEN (`ptc`.`transaction_class_code` = 'LOAN_AMORTIZATION') THEN `pct`.`record_id` ELSE '' END) AS `record_id`,
	(CASE WHEN (`ptc`.`transaction_class_code` = 'LOAN_AMORTIZATION') THEN ROUND(AES_DECRYPT(`pl`.`beginning_balance`,`encryption_key`()),2) ELSE 0 END) AS `beginning_balance`,
	(CASE WHEN (`ptc`.`transaction_class_code` = 'LOAN_AMORTIZATION') THEN ROUND(AES_DECRYPT(`pl`.`running_balance`,`encryption_key`()),2) ELSE 0 END) AS `running_balance`,
	`t`.`payroll_date` AS `payroll_date`,
	`t`.`date_from` AS `date_from`,
	`t`.`date_to` AS `date_to`,
	`tc`.`taxcode` AS `taxcode`,
	`getcompany_contact`(`pct`.`company_id`,'Phone') AS `phone_no`,
	`getcompany_contact`(`pct`.`company_id`,'Fax') AS `fax_no` 
FROM ((((((((((((((`ww_payroll_closed_transaction` `pct` 
		JOIN `ww_users` `u` ON((`pct`.`employee_id` = `u`.`user_id`))) 
		JOIN `ww_partners` `p` ON((`u`.`user_id` = `p`.`user_id`))) 
		JOIN `ww_partners_personal` `ppe` ON((`p`.`partner_id` = `ppe`.`partner_id`))) 
		JOIN `ww_taxcode` `tc` ON((`tc`.`taxcode_id` = `ppe`.`key_value`))) 
		JOIN `ww_users_profile` `up` ON((`u`.`user_id` = `up`.`user_id`))) 
		JOIN `ww_payroll_partners` `pp` ON((`pp`.`user_id` = `u`.`user_id`))) 
		JOIN `ww_users_department` `d` ON((`d`.`department_id` = `up`.`department_id`))) 
		JOIN `ww_users_company` `uc` ON((`uc`.`company_id` = `pp`.`company_id`))) 
		LEFT JOIN `ww_payroll_period` `t` ON((`t`.`payroll_period_id` = `pct`.`period_id`))) 
		LEFT JOIN `ww_payroll_transaction` `pt` ON((`pt`.`transaction_id` = `pct`.`transaction_id`))) 
		LEFT JOIN `ww_payroll_transaction_class` `ptc` ON((`pt`.`transaction_class_id` = `ptc`.`transaction_class_id`))) 
		LEFT JOIN `ww_payroll_partners_loan` `pl` ON((`pl`.`partner_loan_id` = `pct`.`record_id`))) 
		LEFT JOIN `ww_users_project` `uproj` ON((`pct`.`project_id` = `uproj`.`project_id`))) 
		LEFT JOIN `ww_payroll_rate_type` `prt` ON((`pct`.`payroll_rate_type_id` = `prt`.`payroll_rate_type_id`))) 
		WHERE ((`pct`.`on_hold` = 0) AND (`ppe`.`key` = 'taxcode'))$$