<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][1]['payroll_partners_previous_employer.prev_tax_w_held'] = array(
	'f_id' => 13,
	'fg_id' => 1,
	'label' => 'Previous Tax With Held',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_tax_w_held',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 12,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_total_taxable'] = array(
	'f_id' => 12,
	'fg_id' => 1,
	'label' => 'Previous Total Taxable',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_total_taxable',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 12,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_taxable_salaries'] = array(
	'f_id' => 11,
	'fg_id' => 1,
	'label' => 'Previous Taxable Salaries',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_taxable_salaries',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_taxable_thirten_month'] = array(
	'f_id' => 10,
	'fg_id' => 1,
	'label' => 'Previous Taxable Thirteenth Month',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_taxable_thirten_month',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_taxable_basic_salary'] = array(
	'f_id' => 9,
	'fg_id' => 1,
	'label' => 'Previoius Taxable Basic Salary',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_taxable_basic_salary',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_nontax_comp_income'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Previous Nontax Comp Income',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_nontax_comp_income',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_taxable_basic_salary'] = array(
	'f_id' => 8,
	'fg_id' => 1,
	'label' => 'Previous Taxable Basic Salary',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_taxable_basic_salary',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_nontax_salaries'] = array(
	'f_id' => 7,
	'fg_id' => 1,
	'label' => 'Previous Nontax Salaries',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_nontax_salaries',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_nontax_sss_etc'] = array(
	'f_id' => 6,
	'fg_id' => 1,
	'label' => 'Previous Nontax SSS Etc',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_nontax_sss_etc',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_nontax_deminimis'] = array(
	'f_id' => 5,
	'fg_id' => 1,
	'label' => 'Previous Nontax Deminimis',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_nontax_deminimis',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.prev_nontax_thirten_month'] = array(
	'f_id' => 4,
	'fg_id' => 1,
	'label' => 'Previous Nontax Thirteenth Month',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'prev_nontax_thirten_month',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.address'] = array(
	'f_id' => 3,
	'fg_id' => 1,
	'label' => 'Previous Company Address',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'address',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.company_name'] = array(
	'f_id' => 2,
	'fg_id' => 1,
	'label' => 'Previous Company Name',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'company_name',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][1]['payroll_partners_previous_employer.user_id'] = array(
	'f_id' => 1,
	'fg_id' => 1,
	'label' => 'Employee Name',
	'description' => '',
	'table' => 'payroll_partners_previous_employer',
	'column' => 'user_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'user',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'full_name',
		'value' => 'user_id',
		'textual_value_column' => ''
	)
);
