<?php if (!defined('BASEPATH')) exit('No direct script access allowed');
$config["edit_cached_query"] = 'SELECT 
`ww_training_application`.`training_application_id` as record_id, 
`ww_training_application`.`created_on` as "training_application.created_on", 
`ww_training_application`.`created_by` as "training_application.created_by", 
`ww_training_application`.`modified_on` as "training_application.modified_on", 
`ww_training_application`.`modified_by` as "training_application.modified_by", 
ww_training_application.approver_remarks as "training_application.approver_remarks", 
ww_training_application.remarks as "training_application.remarks", 
ww_training_application.remaining_allocated as "training_application.remaining_allocated", 
ww_training_application.remaining_stb as "training_application.remaining_stb", 
ww_training_application.idp_completion as "training_application.idp_completion", 
ww_training_application.excess_ctb as "training_application.excess_ctb", 
ww_training_application.remaining_ctb as "training_application.remaining_ctb", 
ww_training_application.ctb as "training_application.ctb", 
ww_training_application.budgeted as "training_application.budgeted", 
ww_training_application.excess_stb as "training_application.excess_stb", 
ww_training_application.itb as "training_application.itb", 
ww_training_application.investment as "training_application.investment", 
ww_training_application.service_bond as "training_application.service_bond", 
ww_training_application.stb as "training_application.stb", 
ww_training_application.allocated as "training_application.allocated", 
ww_training_application.excess_itb as "training_application.excess_itb", 
ww_training_application.remaining_itb as "training_application.remaining_itb", 
ww_training_application.note as "training_application.note", 
ww_training_application.competency as "training_application.competency", 
ww_training_application.areas_development as "training_application.areas_development", 
ww_training_application.total_investment_pgsa as "training_application.total_investment_pgsa", 
ww_training_application.total_training_hour as "training_application.total_training_hour", 
ww_training_application.venue as "training_application.venue", 
ww_training_application.training_provider as "training_application.training_provider", 
ww_training_application.training_course_id as "training_application.training_course_id", 
DATE_FORMAT(ww_training_application.date_to, \'%M %d, %Y\') as "training_application.date_to", 
DATE_FORMAT(ww_training_application.date_from, \'%M %d, %Y\') as "training_application.date_from", 
ww_training_application.training_type as "training_application.training_type", 
ww_training_application.user_id as "training_application.user_id"
FROM (`ww_training_application`)
WHERE `ww_training_application`.`training_application_id` = "{$record_id}"';