<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['fields'] = array();
$config['fields'][6]['training_application.approver_remarks'] = array(
	'f_id' => 29,
	'fg_id' => 6,
	'label' => 'Remarks (Approver)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'approver_remarks',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 27,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.remarks'] = array(
	'f_id' => 30,
	'fg_id' => 6,
	'label' => 'Remarks (HR)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'remarks',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 28,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.remaining_allocated'] = array(
	'f_id' => 25,
	'fg_id' => 6,
	'label' => 'Remaining Budget After Re-allocation',
	'description' => '',
	'table' => 'training_application',
	'column' => 'remaining_allocated',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 18,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.remaining_stb'] = array(
	'f_id' => 17,
	'fg_id' => 6,
	'label' => 'Remaining Budget (Supplemental)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'remaining_stb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 16,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.idp_completion'] = array(
	'f_id' => 27,
	'fg_id' => 6,
	'label' => '% of IDP',
	'description' => '',
	'table' => 'training_application',
	'column' => 'idp_completion',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 25,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.excess_ctb'] = array(
	'f_id' => 28,
	'fg_id' => 6,
	'label' => 'Amount in Excess of CTB',
	'description' => '',
	'table' => 'training_application',
	'column' => 'excess_ctb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 26,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.remaining_ctb'] = array(
	'f_id' => 26,
	'fg_id' => 6,
	'label' => 'Remaining Budget (Common)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'remaining_ctb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 24,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.ctb'] = array(
	'f_id' => 24,
	'fg_id' => 6,
	'label' => 'Common Training Budget',
	'description' => '',
	'table' => 'training_application',
	'column' => 'ctb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 23,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.budgeted'] = array(
	'f_id' => 21,
	'fg_id' => 6,
	'label' => 'Not Budgeted / Re-allocation',
	'description' => '',
	'table' => 'training_application',
	'column' => 'budgeted',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 20,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.excess_stb'] = array(
	'f_id' => 19,
	'fg_id' => 6,
	'label' => 'Amount in Excess of Supplemental',
	'description' => '',
	'table' => 'training_application',
	'column' => 'excess_stb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 18,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.itb'] = array(
	'f_id' => 18,
	'fg_id' => 6,
	'label' => 'Individual Training Budget',
	'description' => '',
	'table' => 'training_application',
	'column' => 'itb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 17,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.investment'] = array(
	'f_id' => 16,
	'fg_id' => 6,
	'label' => 'Investment',
	'description' => '',
	'table' => 'training_application',
	'column' => 'investment',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 15,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.service_bond'] = array(
	'f_id' => 14,
	'fg_id' => 6,
	'label' => 'With Service Bond',
	'description' => '',
	'table' => 'training_application',
	'column' => 'service_bond',
	'uitype_id' => 3,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 13,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][6]['training_application.stb'] = array(
	'f_id' => 15,
	'fg_id' => 6,
	'label' => 'Supplemental Budget',
	'description' => '',
	'table' => 'training_application',
	'column' => 'stb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 14,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.allocated'] = array(
	'f_id' => 23,
	'fg_id' => 4,
	'label' => 'Re-allocation from',
	'description' => '',
	'table' => 'training_application',
	'column' => 'allocated',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 22,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'training_type',
		'value' => 'type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.excess_itb'] = array(
	'f_id' => 22,
	'fg_id' => 4,
	'label' => 'Amount in Excess of ITB',
	'description' => '',
	'table' => 'training_application',
	'column' => 'excess_itb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 21,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.remaining_itb'] = array(
	'f_id' => 20,
	'fg_id' => 4,
	'label' => 'Remaining Budget (Individual)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'remaining_itb',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 19,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.note'] = array(
	'f_id' => 13,
	'fg_id' => 4,
	'label' => 'NOTE: (If Training will exceed in 1 Month):',
	'description' => '',
	'table' => 'training_application',
	'column' => 'note',
	'uitype_id' => 2,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 12,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.competency'] = array(
	'f_id' => 12,
	'fg_id' => 4,
	'label' => 'Competency',
	'description' => '',
	'table' => 'training_application',
	'column' => 'competency',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 11,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_category',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'category',
		'value' => 'category_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.areas_development'] = array(
	'f_id' => 11,
	'fg_id' => 4,
	'label' => 'Areas for Development',
	'description' => '',
	'table' => 'training_application',
	'column' => 'areas_development',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 10,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.total_investment_pgsa'] = array(
	'f_id' => 10,
	'fg_id' => 4,
	'label' => 'Estimate Investment (Subject for revision by HR):',
	'description' => '',
	'table' => 'training_application',
	'column' => 'total_investment_pgsa',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 9,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.total_training_hour'] = array(
	'f_id' => 9,
	'fg_id' => 4,
	'label' => 'Total Training Hours',
	'description' => '',
	'table' => 'training_application',
	'column' => 'total_training_hour',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 8,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.venue'] = array(
	'f_id' => 8,
	'fg_id' => 4,
	'label' => 'Venue',
	'description' => '',
	'table' => 'training_application',
	'column' => 'venue',
	'uitype_id' => 1,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 7,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.training_provider'] = array(
	'f_id' => 7,
	'fg_id' => 4,
	'label' => 'Training Provider',
	'description' => '',
	'table' => 'training_application',
	'column' => 'training_provider',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 6,
	'datatype' => '',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_provider',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'provider',
		'value' => 'provider_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.training_course_id'] = array(
	'f_id' => 6,
	'fg_id' => 4,
	'label' => 'Training Course',
	'description' => '',
	'table' => 'training_application',
	'column' => 'training_course_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 5,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_course',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'course',
		'value' => 'course_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.date_to'] = array(
	'f_id' => 5,
	'fg_id' => 4,
	'label' => 'Date of Program (To)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'date_to',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 4,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.date_from'] = array(
	'f_id' => 4,
	'fg_id' => 4,
	'label' => 'Date of Program (From)',
	'description' => '',
	'table' => 'training_application',
	'column' => 'date_from',
	'uitype_id' => 6,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 3,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0
);
$config['fields'][4]['training_application.training_type'] = array(
	'f_id' => 3,
	'fg_id' => 4,
	'label' => 'Training Type',
	'description' => '',
	'table' => 'training_application',
	'column' => 'training_type',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 2,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'training_type',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'training_type',
		'value' => 'type_id',
		'textual_value_column' => ''
	)
);
$config['fields'][4]['training_application.user_id'] = array(
	'f_id' => 2,
	'fg_id' => 4,
	'label' => 'Employee',
	'description' => '',
	'table' => 'training_application',
	'column' => 'user_id',
	'uitype_id' => 4,
	'display_id' => 3,
	'quick_edit' => 1,
	'sequence' => 1,
	'datatype' => 'required',
	'active' => '1',
	'encrypt' => 0,
	'searchable' => array(
		'type_id' => '1',
		'table' => 'users',
		'multiple' => 0,
		'group_by' => '',
		'label' => 'full_name',
		'value' => 'user_id',
		'textual_value_column' => ''
	)
);
