<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['system'] = array();
$config['system']['themes_path'] = "base_path() . '/themes/'";
$config['system']['application_title'] = "OCLP Holdings, Inc.";
$config['system']['use_logo'] = 1;
$config['system']['logo'] = "uploads/system/login/company_logo.png";
$config['system']['author'] = "Tirso garcia jr.";
$config['system']['footer'] = "© Emplopad";
$config['system']['copyright_details'] = "© Emplopad";
$config['system']['description'] = "emplopad";
$config['system']['keywords'] = "emplopad";
$config['system']['copyright'] = "© Emplopad";
$config['system']['URL'] = "http://hris.ortigasland.com.ph/uat.emplopad.update/";
$config['system']['header_logo'] = "uploads/system/header/ortigas_land_logo (1).png";
$config['system']['print_logo'] = "uploads/system/print/ortigas_land_corporation.png";
$config['system']['bg_image'] = "assets/img/bg/3.jpg";
$config['system']['bg_image'] = "assets/img/bg/1.jpg";
$config['system']['bg_image'] = "assets/img/bg/2.jpg";
$config['system']['bg_image'] = "assets/img/bg/3.jpg";
$config['system']['bg_image'] = "assets/img/bg/L1_02.jpg";
$config['system']['bg_image'] = "assets/img/bg/L2_02.jpg";
$config['system']['bg_image'] = "assets/img/bg/L3_02.jpg";
$config['system']['bg_image'] = "assets/img/bg/L4_02.jpg";
$config['system']['bg_image'] = "assets/img/bg/C1_02.jpg";
$config['system']['bg_image'] = "assets/img/bg/C2_02.jpg";
