<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

$config['system'] = array();
$config['system']['themes_path'] = "base_path() . '/themes/'";
$config['system']['application_title'] = "OCLP Holdings, Inc.";
$config['system']['use_logo'] = 1;
$config['system']['logo'] = "uploads/system/login/company_logo.png";
$config['system']['author'] = "Tirso garcia jr.";
$config['system']['footer'] = "© Emplopad";
$config['system']['copyright_details'] = "© Emplopad";
$config['system']['description'] = "emplopad";
$config['system']['keywords'] = "emplopad";
$config['system']['copyright'] = "© Emplopad";
$config['system']['URL'] = "http://hris.abrahamholdings.ph/emplopad/";
$config['system']['header_logo'] = "uploads/system/header/ortigas_land_logo_icon.png";
$config['system']['print_logo'] = "";
$config['system']['bg_image'] = "assets/img/bg/3.jpg";
$config['system']['bg_image'] = "assets/img/bg/1.jpg";
$config['system']['bg_image'] = "assets/img/bg/2.jpg";
$config['system']['bg_image'] = "assets/img/bg/3.jpg";
